### ISSUE TITLE
Chirpstack compilation error due to rquickjs sys v0.3.1

### ISSUE THREAD

**Issue by Victccmc** [chirpstack/chirpstack-openwrt-feed#1]
I have tried using different versions of rust (1.68,1.69), and different versions of chipstack (4.4.0, 4.4.3) have all reported the same error，The error message is as follows：

get/aarch64-unknown-linux-musl/stripped/deps/libzeroize-49481cdbe96133ee.rmeta --cap-lints allow -Ctarget-feature=-crt-static -Clink-args=-lssp_nonshared --cfg has_i128`
   Compiling mime_guess v2.0.4
     Running `/workspace/firefly/openwrt_rk3568/lede/build_dir/target-aarch64_generic_musl/chirpstack-4.4.3/target/stripped/build/mime_guess-b48c3c2c6620783f/build-script-build`
   Compiling serde_with_macros v3.1.0
     Running `rustc --crate-name serde_with_macros --edition=2021 /workspace/firefly/openwrt_rk3568/lede/staging_dir/hostpkg/cargo/registry/src/github.com-1ecc6299db9ec823/serde_with_macros-3.1.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=200 --crate-type proc-macro --emit=dep-info,link -C prefer-dynamic -C embed-bitcode=no -C debug-assertions=off -C metadata=c786df2ca8e5ceaa -C extra-filename=-c786df2ca8e5ceaa --out-dir /workspace/firefly/openwrt_rk3568/lede/build_dir/target-aarch64_generic_musl/chirpstack-4.4.3/target/stripped/deps -C strip=symbols -L dependency=/workspace/firefly/openwrt_rk3568/lede/build_dir/target-aarch64_generic_musl/chirpstack-4.4.3/target/stripped/deps --extern darling=/workspace/firefly/openwrt_rk3568/lede/build_dir/target-aarch64_generic_musl/chirpstack-4.4.3/target/stripped/deps/libdarling-b5ea586e51455677.rlib --extern proc_macro2=/workspace/firefly/openwrt_rk3568/lede/build_dir/target-aarch64_generic_musl/chirpstack-4.4.3/target/stripped/deps/libproc_macro2-d75c02e7a206be7b.rlib --extern quote=/workspace/firefly/openwrt_rk3568/lede/build_dir/target-aarch64_generic_musl/chirpstack-4.4.3/target/stripped/deps/libquote-ac3dc7051a62a1b6.rlib --extern syn=/workspace/firefly/openwrt_rk3568/lede/build_dir/target-aarch64_generic_musl/chirpstack-4.4.3/target/stripped/deps/libsyn-28555f044ef7b2ec.rlib --extern proc_macro --cap-lints allow`
   Compiling rquickjs-sys v0.3.1
     Running `rustc --crate-name rquickjs_sys --edition=2018 /workspace/firefly/openwrt_rk3568/lede/staging_dir/hostpkg/cargo/registry/src/github.com-1ecc6299db9ec823/rquickjs-sys-0.3.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=200 --crate-type lib --emit=dep-info,metadata,link -C opt-level=s -C linker-plugin-lto -C codegen-units=1 --cfg 'feature="bindgen"' --cfg 'feature="bindgen-rs"' --cfg 'feature="exports"' -C metadata=ec94682cd9133bb7 -C extra-filename=-ec94682cd9133bb7 --out-dir /workspace/firefly/openwrt_rk3568/lede/build_dir/target-aarch64_generic_musl/chirpstack-4.4.3/target/aarch64-unknown-linux-musl/stripped/deps --target aarch64-unknown-linux-musl -C linker=aarch64-openwrt-linux-musl-gcc -C strip=symbols -L dependency=/workspace/firefly/openwrt_rk3568/lede/build_dir/target-aarch64_generic_musl/chirpstack-4.4.3/target/aarch64-unknown-linux-musl/stripped/deps -L dependency=/workspace/firefly/openwrt_rk3568/lede/build_dir/target-aarch64_generic_musl/chirpstack-4.4.3/target/stripped/deps --cap-lints allow -Ctarget-feature=-crt-static -Clink-args=-lssp_nonshared -L native=/workspace/firefly/openwrt_rk3568/lede/build_dir/target-aarch64_generic_musl/chirpstack-4.4.3/target/aarch64-unknown-linux-musl/stripped/build/rquickjs-sys-cf7df2c41dc2adb3/out -l static=quickjs`
error[E0422]: cannot find struct, variant or union type `JSValueUnion` in this scope
  --> /workspace/firefly/openwrt_rk3568/lede/staging_dir/hostpkg/cargo/registry/src/github.com-1ecc6299db9ec823/rquickjs-sys-0.3.1/src/inlines/ptr_64.rs:34:12
   |
34 |         u: JSValueUnion { int32: val },
   |            ^^^^^^^^^^^^ not found in this scope

error[E0422]: cannot find struct, variant or union type `JSValueUnion` in this scope
  --> /workspace/firefly/openwrt_rk3568/lede/staging_dir/hostpkg/cargo/registry/src/github.com-1ecc6299db9ec823/rquickjs-sys-0.3.1/src/inlines/ptr_64.rs:42:12
   |
42 |         u: JSValueUnion { ptr },
   |            ^^^^^^^^^^^^ not found in this scope

error[E0422]: cannot find struct, variant or union type `JSValueUnion` in this scope
  --> /workspace/firefly/openwrt_rk3568/lede/staging_dir/hostpkg/cargo/registry/src/github.com-1ecc6299db9ec823/rquickjs-sys-0.3.1/src/inlines/ptr_64.rs:54:8
   |
54 |     u: JSValueUnion { float64: f64::NAN },
   |        ^^^^^^^^^^^^ not found in this scope

error[E0422]: cannot find struct, variant or union type `JSValueUnion` in this scope
  --> /workspace/firefly/openwrt_rk3568/lede/staging_dir/hostpkg/cargo/registry/src/github.com-1ecc6299db9ec823/rquickjs-sys-0.3.1/src/inlines/ptr_64.rs:61:12
   |
61 |         u: JSValueUnion { float64: d },
   |            ^^^^^^^^^^^^ not found in this scope

error[E0071]: expected struct, variant or union type, found `u64`
  --> /workspace/firefly/openwrt_rk3568/lede/staging_dir/hostpkg/cargo/registry/src/github.com-1ecc6299db9ec823/rquickjs-sys-0.3.1/src/inlines/ptr_64.rs:52:29
   |
52 | pub const JS_NAN: JSValue = JSValue {
   |                             ^^^^^^^ not a struct

error[E0610]: `u64` is a primitive type and therefore doesn't have fields
 --> /workspace/firefly/openwrt_rk3568/lede/staging_dir/hostpkg/cargo/registry/src/github.com-1ecc6299db9ec823/rquickjs-sys-0.3.1/src/inlines/ptr_64.rs:3:7
  |
3 |     v.tag as _
  |       ^^^

error[E0610]: `u64` is a primitive type and therefore doesn't have fields
  --> /workspace/firefly/openwrt_rk3568/lede/staging_dir/hostpkg/cargo/registry/src/github.com-1ecc6299db9ec823/rquickjs-sys-0.3.1/src/inlines/ptr_64.rs:13:7
   |
13 |     v.u.int32
   |       ^

error[E0610]: `u64` is a primitive type and therefore doesn't have fields
  --> /workspace/firefly/openwrt_rk3568/lede/staging_dir/hostpkg/cargo/registry/src/github.com-1ecc6299db9ec823/rquickjs-sys-0.3.1/src/inlines/ptr_64.rs:18:7
   |
18 |     v.u.int32 != 0
   |       ^

error[E0610]: `u64` is a primitive type and therefore doesn't have fields
  --> /workspace/firefly/openwrt_rk3568/lede/staging_dir/hostpkg/cargo/registry/src/github.com-1ecc6299db9ec823/rquickjs-sys-0.3.1/src/inlines/ptr_64.rs:23:7
   |
23 |     v.u.float64
   |       ^

error[E0610]: `u64` is a primitive type and therefore doesn't have fields
  --> /workspace/firefly/openwrt_rk3568/lede/staging_dir/hostpkg/cargo/registry/src/github.com-1ecc6299db9ec823/rquickjs-sys-0.3.1/src/inlines/ptr_64.rs:28:7
   |
28 |     v.u.ptr
   |       ^

error[E0071]: expected struct, variant or union type, found `u64`
  --> /workspace/firefly/openwrt_rk3568/lede/staging_dir/hostpkg/cargo/registry/src/github.com-1ecc6299db9ec823/rquickjs-sys-0.3.1/src/inlines/ptr_64.rs:33:5
   |
33 |     JSValue {
   |     ^^^^^^^ not a struct

error[E0071]: expected struct, variant or union type, found `u64`
  --> /workspace/firefly/openwrt_rk3568/lede/staging_dir/hostpkg/cargo/registry/src/github.com-1ecc6299db9ec823/rquickjs-sys-0.3.1/src/inlines/ptr_64.rs:41:5
   |
41 |     JSValue {
   |     ^^^^^^^ not a struct

error[E0071]: expected struct, variant or union type, found `u64`
  --> /workspace/firefly/openwrt_rk3568/lede/staging_dir/hostpkg/cargo/registry/src/github.com-1ecc6299db9ec823/rquickjs-sys-0.3.1/src/inlines/ptr_64.rs:59:5
   |
59 |     JSValue {
   |     ^^^^^^^ not a struct

error[E0610]: `u64` is a primitive type and therefore doesn't have fields
  --> /workspace/firefly/openwrt_rk3568/lede/staging_dir/hostpkg/cargo/registry/src/github.com-1ecc6299db9ec823/rquickjs-sys-0.3.1/src/inlines/ptr_64.rs:71:10
   |
71 |     if v.tag != JS_TAG_FLOAT64 as _ {
   |          ^^^

error[E0610]: `u64` is a primitive type and therefore doesn't have fields
  --> /workspace/firefly/openwrt_rk3568/lede/staging_dir/hostpkg/cargo/registry/src/github.com-1ecc6299db9ec823/rquickjs-sys-0.3.1/src/inlines/ptr_64.rs:74:22
   |
74 |     let u = U { d: v.u.float64 };
   |                      ^

Some errors have detailed explanations: E0071, E0422, E0610.
For more information about an error, try `rustc --explain E0071`.
error: could not compile `rquickjs-sys` due to 15 previous errors

Caused by:
  process didn't exit successfully: `rustc --crate-name rquickjs_sys --edition=2018 /workspace/firefly/openwrt_rk3568/lede/staging_dir/hostpkg/cargo/registry/src/github.com-1ecc6299db9ec823/rquickjs-sys-0.3.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=200 --crate-type lib --emit=dep-info,metadata,link -C opt-level=s -C linker-plugin-lto -C codegen-units=1 --cfg 'feature="bindgen"' --cfg 'feature="bindgen-rs"' --cfg 'feature="exports"' -C metadata=ec94682cd9133bb7 -C extra-filename=-ec94682cd9133bb7 --out-dir /workspace/firefly/openwrt_rk3568/lede/build_dir/target-aarch64_generic_musl/chirpstack-4.4.3/target/aarch64-unknown-linux-musl/stripped/deps --target aarch64-unknown-linux-musl -C linker=aarch64-openwrt-linux-musl-gcc -C strip=symbols -L dependency=/workspace/firefly/openwrt_rk3568/lede/build_dir/target-aarch64_generic_musl/chirpstack-4.4.3/target/aarch64-unknown-linux-musl/stripped/deps -L dependency=/workspace/firefly/openwrt_rk3568/lede/build_dir/target-aarch64_generic_musl/chirpstack-4.4.3/target/stripped/deps --cap-lints allow -Ctarget-feature=-crt-static -Clink-args=-lssp_nonshared -L native=/workspace/firefly/openwrt_rk3568/lede/build_dir/target-aarch64_generic_musl/chirpstack-4.4.3/target/aarch64-unknown-linux-musl/stripped/build/rquickjs-sys-cf7df2c41dc2adb3/out -l static=quickjs` (exit status: 1)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `chirpstack v4.4.3 (/workspace/firefly/openwrt_rk3568/lede/build_dir/target-aarch64_generic_musl/chirpstack-4.4.3/chirpstack)`, intermediate artifacts can be found at `/workspace/firefly/openwrt_rk3568/lede/build_dir/target-aarch64_generic_musl/chirpstack-4.4.3/target`
Makefile:73: recipe for target '/workspace/firefly/openwrt_rk3568/lede/build_dir/target-aarch64_generic_musl/chirpstack-4.4.3/.built' failed
make[3]: *** [/workspace/firefly/openwrt_rk3568/lede/build_dir/target-aarch64_generic_musl/chirpstack-4.4.3/.built] Error 101
make[3]: Leaving directory '/workspace/firefly/openwrt_rk3568/lede/feeds/chirpstack/chirpstack/chirpstack'
time: package/feeds_local/chirpstack/chirpstack/compile#282.48#85.03#427.68
    ERROR: package/feeds_local/chirpstack/chirpstack failed to build.
package/Makefile:114: recipe for target 'package/feeds_local/chirpstack/chirpstack/compile' failed
make[2]: *** [package/feeds_local/chirpstack/chirpstack/compile] Error 1
make[2]: Leaving directory '/workspace/firefly/openwrt_rk3568/lede'
package/Makefile:110: recipe for target '/workspace/firefly/openwrt_rk3568/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_compile' failed
make[1]: *** [/workspace/firefly/openwrt_rk3568/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workspace/firefly/openwrt_rk3568/lede'
/workspace/firefly/openwrt_rk3568/lede/include/toplevel.mk:228: recipe for target 'world' failed
make: *** [world] Error 2

The compilation environment is as follows：
The openwrt version is R21;
kernel version:5.19.1
cat /etc/openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_TARGET='rockchip/armv8'
DISTRIB_ARCH='aarch64_generic'
DISTRIB_TAINTS='no-all override'
DISTRIB_REVISION='R22.8.2'
DISTRIB_DESCRIPTION='OpenWrt '
gcc version:toolchain-aarch64_generic_gcc-8.4.0_musl

I guess it's because the different versions of the compilers result in different domain definitions or other。

**Comment by brocaar** [comment]
Are you building using the OpenWrt 23.05 branch? That is what I'm using and testing against. For my build environment see:
https://github.com/chirpstack/chirpstack-gateway-os

**Comment by Victccmc** [comment]
> 
Thank you for your reply，
My gateway just supports version OpenWrt 22.8 , So I did not compile using OpenWrt 23.05 branch. 
I noticed the same error report：https://github.com/chirpstack/chirpstack-gateway-os/issues/87,also compilation failed on a 64 bit system，My cross compilation tool is also 64 bit，Is this error possibly related to 64 bit？

**Comment by brocaar** [comment]
Please note that OpenWrt < 23.05 does not support Rust, it was only recently added.

> Is this error possibly related to 64 bit？

Maybe, I have not yet tried cross-compiling to OpenWrt 64 bit target. However, ChirpStack itself is cross-compiled for AMD64 without any issues.

**Comment by brocaar** [comment]
I'm closing this issue. As mentioned in the README, building these packages is tested against OpenWrt 23.05 (more specifically, against the targets in https://github.com/chirpstack/chirpstack-gateway-os). It is also the first release supporting Rust. Backporting Rust to an older OpenWrt version might work, but I do not have the bandwidth to support his.
